POST http://localhost:8081/svc2-add HTTP/1.1
content-type: application/json

{
    "a": "1",
    "b": "2"
}

###
POST http://localhost:8081/api/hello HTTP/1.1
content-type: application/json

{
    "a": "1",
    "b": "2"
}

### 

POST http://vm.poridhi.io/api/hello HTTP/1.1
content-type: application/json

{
    "a": "1",
    "b": "2"
}

###
POST http://localhost:3000/api/svc HTTP/1.1
content-type: application/json

{
    "a": "1",
    "b": "2"
}

###
POST http://vm.poridhi.io/api/svc HTTP/1.1
content-type: application/json

{
    "a": "1",
    "b": "2"
}